version: '3'

services:
  humble_garden:
    image: humble_garden
    tty: True
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        ROS_DISTRO: humble
    environment:
      - "PYTHONUNBUFFERED=1"
      - DISPLAY
      - "QT_X11_NO_MITSHM=1"
      - NVIDIA_VISIBLE_DEVICES=all # for docker-nvidia2
      - NVIDIA_DRIVER_CAPABILITIES=all # for docker-nvidia2
      - TURTLEBOT3_MODEL=burger
      - XDG_RUNTIME_DIR 
      - __NV_PRIME_RENDER_OFFLOAD
      - __GLX_VENDOR_LIBRARY_NAME
    working_dir: "/home/ros/"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    privileged: True
    network_mode: host

networks:
  default:
    external:
      name: turtlebot
